apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  namespace: antik-moderne
spec:
  type: NodePort # Change to ClusterIP if you don't need external access
  ports:
    - port: 3000 # Port exposed by the service
      targetPort: 3000 # Port your app listens on
      nodePort: 30001
  selector:
    app: frontend-app
